title: KMUpower
email: info@kmupower.ch
description: "Wir ermächtigen KMUs durch digitale Exzellenz."
url: "https://marcelehlmann.github.io"
baseurl: "/KMUpower"

plugins:
  - jekyll-seo-tag
  - jekyll-include-cache
  - jekyll-remote-theme

remote_theme: "mmistakes/minimal-mistakes"

lang: de
author:
  name: Marcel Lehmann
  avatar: "/assets/images/avatar.jpg"
  bio: "Gründer & CEO | Microsoft MVP | Digitalisierungsexperte für KMU im DACH-Raum"

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: single
      author_profile: false
      seo:
        type: website