title: KMUpower
description: Ihre professionelle Webseite von KMUpower.
author: Marcel Lehmann # Oder der Name des Autors/Unternehmens

# Die baseurl und url sind wichtig für korrekte Links, besonders auf GitHub Pages.
# Wenn Ihre Seite unter https://<BENUTZERNAME>.github.io/<REPOSITORY-NAME>/ gehostet wird:
# baseurl: "/<REPOSITORY-NAME>" # z.B. /KMUpower
# url: "https://<BENUTZERNAME>.github.io"
# Wenn es eine benutzerdefinierte Domain ist oder eine User/Orga-Seite (https://<BENUTZERNAME>.github.io/):
baseurl: "/KMUpower" # Leer lassen, wenn im Root-Verzeichnis der Domain
url: "https://marcelehmann.github.io" # Vollständige URL Ihrer Seite, z.B. https://www.kmupower.ch

# Build settings
markdown: kramdown
permalink: pretty # Für saubere URLs

plugins:
  - jekyll-feed    # Für einen RSS-Feed
  - jekyll-seo-tag # Für automatische SEO-Meta-Tags

# Standardwerte für Seiten und Beiträge (optional)
defaults:
  - scope:
      path: "" # alle Dateien
    values:
      layout: "default"

# Dateien/Ordner, die vom Build ausgeschlossen werden sollen
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - LICENSE