# Site settings
title: CheckYield
email: info@checkyield.com
description: >- # this means to ignore newlines until "baseurl:"
  CheckYield - Ihr Experte für Microsoft Power Platform Entwicklung und Beratung.
  Maßgeschneiderte Lösungen für Power BI, Power Apps und Power Automate.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://checkyield.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: checkyield
github_username:  checkyield
logo: /assets/images/logo.png

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Collections
collections:
  services:
    output: true
    permalink: /:collection/:name/
  
# Default front matter
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "services"
    values:
      layout: "service"
  - scope:
      path: ""
    values:
      layout: "default"

# Exclude from processing.
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

